name: "Greenshoots"
description: "Photography for industry and science."

baseurl: file:///C:/Users/sam/Documents/GitHub/greenshoots/_site/
paginate: 100

permalink: /:categories/:title
pygments: false

future: false  