name: "Greenshoots"
description: "Photography for industry and science."

#baseurl: file:///C:/Users/sam/Documents/GitHub/greenshoots/_site/
# baseurl: /
 baseurl: /greenshoots/

permalink: /:categories/:title
pygments: false

future: false  