name: "Greenshoots"
description: "Photography for industry and science."

# local
# baseurl: /_site/

# github
baseurl: "/greenshoots/"

# live
# baseurl: "/"

include: ['_redirects']
relative_permalinks: false
permalink: /:categories/:title
highlighter: false

future: false 

markdown: kramdown
