name: "Greenshoots"
description: "Photography for industry and science."

# baseurl: /_site/
# baseurl: C:\Users\sam\Documents\GitHub\greenshoots\_site\

baseurl: "/greenshoots/"

permalink: /:categories/:title
pygments: false

future: false  