name: "Greenshoots"
description: "Photography for industry and science."

# local
# baseurl: /_site/

# github
baseurl: "/greenshoots/"

# live
# baseurl: "/"

permalink: /:categories/:title
pygments: false

future: false  